language: node_js

jobs:
  include:
    - name: linux
      os: linux
      node_js: '10'
      script:
        - npm ci
        - npm run -s compile:linux
        - npm run -s package
        - npm run -s citest
    - name: darwin
      os: osx
      node_js: '10'
      script:
        - npm ci
        - npm run -s compile:darwin
        - npm run -s package
        - npm run -s citest
