version: '{branch} #{build}'
image: Visual Studio 2017
platform: x64
configuration: Release

environment:
  matrix:
    - nodejs_version: "10"
  npm_auth_token:
    secure: pBJzpHmM4Z+rgfqxGj63yLXIKLDc5AjV/bexQ/CjpUfKuoRML71pcYtS/CkqAxhn

install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - where cl
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - npm --version

build_script:
  - npm ci
  - npm run -s compile:win32
  - npm run -s package
  - npm run -s citest

artifacts:
  - path: windows\dcraw.exe
    name: dcraw

deploy_script:
  - cd dist
  - dir
  - ps: '"//registry.npmjs.org/:_authToken=$env:npm_auth_token`n" | out-file "$env:userprofile\.npmrc" -Encoding ASCII'
  - npm whoami
  - npm publish
  on:
    APPVEYOR_REPO_TAG: true

